language: r

sudo: false

dist: trusty

install:
  - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false

Imports:
  - simts
  - imudata

Remotes:
  - SMAC-Group/simts
  - SMAC-Group/imudata

notifications:
    slack: smac-group:EWDAUVsNDTFCD126xDUGJHKK

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
